name: Execucao Diaria do Agendador

on:
  schedule:
    - cron: '5 3 * * *'
  workflow_dispatch: 

jobs:
  rodar-robo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Dependencias
        run: npm install

      - name: Instalar Navegador Playwright
        run: npx playwright install chromium --with-deps

      - name: Executar Script
        run: node agendador.js
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          PREFERRED_TIME: ${{ secrets.PREFERRED_TIME }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
